import React from 'react';
import { Gavel, AlertTriangle, ShieldAlert, ScrollText, CheckCircle2, Bookmark, Landmark, Terminal, Scale } from 'lucide-react';

export const Terms: React.FC = () => {
  return (
    <div className="bg-[#050505] min-h-screen text-white pt-40 pb-32 selection:bg-[#D4AF37] selection:text-black">
      <div className="max-w-5xl mx-auto px-6 space-y-24">
        
        {/* PROTOCOL HEADER */}
        <header className="text-center space-y-8 animate-in fade-in slide-in-from-top-10 duration-1000">
          <div className="inline-flex items-center gap-3 px-8 py-3 rounded-full bg-[#D4AF37]/10 border border-[#D4AF37]/30 text-[#D4AF37] text-[11px] font-black uppercase tracking-[0.6em] mb-4 shadow-2xl backdrop-blur-3xl">
            <Gavel size={18} /> Professional Usage Agreement
          </div>
          <h1 className="text-6xl md:text-9xl font-black uppercase tracking-tighter italic leading-none">
            Terms of <span className="text-[#D4AF37] text-glow">Engagement</span>
          </h1>
          <p className="text-xl md:text-2xl text-white/40 italic max-w-2xl mx-auto leading-relaxed font-medium">
            "By accessing the vault, you acknowledge the parameters of our digital instruments and the sovereign limits of our scholarly registry."
          </p>
          <div className="flex justify-center gap-3 pt-6">
            {[1,2,3,4,5].map(i => <div key={i} className="w-1.5 h-1.5 rounded-full bg-[#D4AF37]/30"></div>)}
          </div>
        </header>

        {/* ENGAGEMENT MODULES */}
        <div className="space-y-16">
          
          {/* 1. INFORMATIONAL NATURE */}
          <section className="relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-[#D4AF37]/20 to-transparent rounded-[4rem] blur-2xl opacity-10 group-hover:opacity-20 transition duration-1000"></div>
            <div className="relative rounded-[4rem] p-12 md:p-20 border border-white/5 bg-[#0a0a0a] overflow-hidden group shadow-2xl">
              <Landmark className="absolute -bottom-16 -right-16 opacity-[0.02] text-[#D4AF37] rotate-12 group-hover:opacity-[0.05] transition-opacity duration-700" size={400} />
              
              <div className="relative z-10 space-y-10">
                <div className="flex items-center gap-6 text-[#D4AF37]">
                  <AlertTriangle size={32} strokeWidth={1.5} />
                  <h2 className="text-3xl font-black uppercase tracking-tighter italic">I. Informational Mandate</h2>
                </div>
                
                <div className="prose prose-invert max-w-none text-white/50 space-y-8 text-xl leading-relaxed italic font-medium">
                  <p>
                    StrongTools provides a suite of digital instruments for <span className="text-white">informational and educational purposes</span> only. While we strive for absolute mathematical precision, the results generated by our calculators, converters, and analytical engines are not to be construed as definitive professional, medical, financial, or legal counsel.
                  </p>
                  <p className="text-lg border-l-2 border-[#D4AF37]/30 pl-8">
                    The user assumes full and absolute responsibility for any actions taken based on the data synthesized within this registry. Verification through primary certified sources is always recommended for critical operations.
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* 2 & 3. INTEGRITY & LIABILITY */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
            <section className="rounded-[3.5rem] p-14 bg-white/[0.02] border border-white/5 space-y-8 hover:border-[#D4AF37]/30 transition-all duration-700 backdrop-blur-xl group">
              <div className="flex items-center gap-5 text-[#D4AF37]">
                <Terminal size={28} className="group-hover:scale-110 transition-transform" />
                <h3 className="text-2xl font-black uppercase tracking-tighter italic text-white">II. Registry Integrity</h3>
              </div>
              <p className="text-white/40 leading-relaxed italic text-lg font-medium">
                We grant you a non-exclusive right to utilize our sovereign tools. Any attempt to <span className="text-white">scrape, reverse-engineer</span>, or disrupt the logical infrastructure of our instruments is a direct violation of this engagement and may result in permanent access revocation.
              </p>
            </section>

            <section className="rounded-[3.5rem] p-14 bg-white/[0.02] border border-white/5 space-y-8 hover:border-[#D4AF37]/30 transition-all duration-700 backdrop-blur-xl group">
              <div className="flex items-center gap-5 text-[#D4AF37]">
                <ShieldAlert size={28} className="group-hover:scale-110 transition-transform" />
                <h3 className="text-2xl font-black uppercase tracking-tighter italic text-white">III. Liability Limits</h3>
              </div>
              <p className="text-white/40 leading-relaxed italic text-lg font-medium">
                StrongTools, its scribes, and architects shall not be held liable for any direct, indirect, or consequential damages resulting from the use or inability to use the instruments provided in this vault. Our service is provided <span className="text-white">"As-Is"</span> without warranties of any kind.
              </p>
            </section>
          </div>

          {/* 4. INTELLECTUAL PROPERTY */}
          <section className="rounded-[4rem] p-12 md:p-20 border border-[#D4AF37]/20 bg-[#D4AF37]/5 space-y-12 shadow-inner">
            <div className="flex items-center gap-6 text-[#D4AF37]">
              <ScrollText size={32} />
              <h2 className="text-3xl font-black uppercase tracking-tighter italic">IV. Intellectual Property & AI</h2>
            </div>
            <div className="prose prose-invert max-w-none text-white/50 text-xl italic font-medium leading-relaxed">
              <p>
                All manuscripts and analytical articles found within our "Chronicles" are synthesized using <span className="text-white">Generative Intelligence</span>. This content remains the sole intellectual property of StrongTools. Any republication or citation of these works must include a clear, canonical backlink to the original StrongTools archive.
              </p>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mt-12">
                <div className="flex items-center gap-4 bg-black/40 p-6 rounded-2xl border border-white/5 group hover:border-[#D4AF37]/40 transition-colors">
                  <CheckCircle2 size={24} className="text-[#D4AF37]" />
                  <span className="text-xs uppercase font-black tracking-[0.2em] text-white">Verify Analytical Results</span>
                </div>
                <div className="flex items-center gap-4 bg-black/40 p-6 rounded-2xl border border-white/5 group hover:border-[#D4AF37]/40 transition-colors">
                  <CheckCircle2 size={24} className="text-[#D4AF37]" />
                  <span className="text-xs uppercase font-black tracking-[0.2em] text-white">No Automated Scraping</span>
                </div>
              </div>
            </div>
          </section>

          {/* GOVERNANCE SUMMARY */}
          <footer className="text-center space-y-10 pt-20">
            <div className="w-16 h-16 bg-[#D4AF37] rounded-[1.5rem] flex items-center justify-center text-black mx-auto shadow-[0_0_50px_rgba(212,175,55,0.3)] -rotate-3 hover:rotate-0 transition-transform cursor-pointer">
              <Bookmark size={32} />
            </div>
            <div className="space-y-4">
              <p className="text-white/30 italic font-medium text-lg leading-relaxed max-w-xl mx-auto">
                These protocols are effective as of the current meridian. Continued access to the vault constitutes a binding acceptance of this professional engagement.
              </p>
            </div>
            
            <div className="pt-20 border-t border-white/5 space-y-6">
              <div className="flex justify-center gap-10 opacity-20">
                 <Scale size={24} />
                 <Gavel size={24} />
                 <Landmark size={24} />
              </div>
              <p className="text-white/10 text-[10px] font-black uppercase tracking-[1.5em] italic">
                Sovereign Archival Governance v4.0.0 • Verified MMXXIV
              </p>
            </div>
          </footer>

        </div>
      </div>
    </div>
  );
};
